- name : start service only if installed
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: absent
    register: installed



   