- name: Create user only on webservers
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: Create deploy user
    ansible.builtin.user:
        name: deploy
        state: present
    when: "'local' in group names"