- name: play variables
  hosts: local
  connection: local
  vars:
    name: murali
    training: devops
  tasks:
    - name: printing variables
      ansible.builtin.debug:
       msg: "iam{{ name }} topper in {{ devops }}"