 - name : install web server based on os
   hosts: local
   become: yes

   tasks:
    - name: install http on redhat
      ansible.builtin.package:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: install apache2 on debain
      ansible.builtin.package:
        name: apache2
        state: present
      when: ansible_os_family == "apache2" 
